// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateGameData, CreateGameErrors, CreateGameResponses, GetBoardData, GetBoardResponses, GetGameData, GetGameErrors, GetGameResponses, JoinGameData, JoinGameErrors, JoinGameResponses, LoginAppleData, LoginAppleErrors, LoginAppleResponses, LoginData, LoginErrors, LoginGoogleData, LoginGoogleErrors, LoginGoogleResponses, LoginResponses, LogoutData, LogoutErrors, LogoutResponses, RefreshData, RefreshErrors, RefreshResponses, RegisterData, RegisterErrors, RegisterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Login Apple
 */
export const loginApple = <ThrowOnError extends boolean = false>(options: Options<LoginAppleData, ThrowOnError>): RequestResult<LoginAppleResponses, LoginAppleErrors, ThrowOnError> => (options.client ?? client).post<LoginAppleResponses, LoginAppleErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/apple',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login Google
 */
export const loginGoogle = <ThrowOnError extends boolean = false>(options: Options<LoginGoogleData, ThrowOnError>): RequestResult<LoginGoogleResponses, LoginGoogleErrors, ThrowOnError> => (options.client ?? client).post<LoginGoogleResponses, LoginGoogleErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/google',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>): RequestResult<LoginResponses, LoginErrors, ThrowOnError> => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Refresh
 */
export const refresh = <ThrowOnError extends boolean = false>(options?: Options<RefreshData, ThrowOnError>): RequestResult<RefreshResponses, RefreshErrors, ThrowOnError> => (options?.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/refresh',
    ...options
});

/**
 * Register
 */
export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>): RequestResult<RegisterResponses, RegisterErrors, ThrowOnError> => (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Board
 */
export const getBoard = <ThrowOnError extends boolean = false>(options?: Options<GetBoardData, ThrowOnError>): RequestResult<GetBoardResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetBoardResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/board/',
    ...options
});

/**
 * Create Game
 */
export const createGame = <ThrowOnError extends boolean = false>(options: Options<CreateGameData, ThrowOnError>): RequestResult<CreateGameResponses, CreateGameErrors, ThrowOnError> => (options.client ?? client).post<CreateGameResponses, CreateGameErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/games/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Game
 */
export const getGame = <ThrowOnError extends boolean = false>(options: Options<GetGameData, ThrowOnError>): RequestResult<GetGameResponses, GetGameErrors, ThrowOnError> => (options.client ?? client).get<GetGameResponses, GetGameErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/games/{game_id}',
    ...options
});

/**
 * Join Game
 */
export const joinGame = <ThrowOnError extends boolean = false>(options: Options<JoinGameData, ThrowOnError>): RequestResult<JoinGameResponses, JoinGameErrors, ThrowOnError> => (options.client ?? client).patch<JoinGameResponses, JoinGameErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/games/{game_id}/join',
    ...options
});
