// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	CreateGameData,
	CreateGameErrors,
	CreateGameResponses,
	GetGameStateData,
	GetGameStateErrors,
	GetGameStateResponses,
	JoinGameData,
	JoinGameErrors,
	JoinGameResponses,
	LoginAppleData,
	LoginAppleErrors,
	LoginAppleResponses,
	LoginData,
	LoginErrors,
	LoginGoogleData,
	LoginGoogleErrors,
	LoginGoogleResponses,
	LoginResponses,
	LogoutData,
	LogoutErrors,
	LogoutResponses,
	RefreshData,
	RefreshErrors,
	RefreshResponses,
	RegisterData,
	RegisterErrors,
	RegisterResponses,
	StartGameData,
	StartGameErrors,
	StartGameResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Login Apple
 */
export const loginApple = <ThrowOnError extends boolean = false>(
	options: Options<LoginAppleData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		LoginAppleResponses,
		LoginAppleErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/apple",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Login Google
 */
export const loginGoogle = <ThrowOnError extends boolean = false>(
	options: Options<LoginGoogleData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		LoginGoogleResponses,
		LoginGoogleErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/google",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(
	options: Options<LoginData, ThrowOnError>,
) =>
	(options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
		responseType: "json",
		url: "/auth/login",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(
	options?: Options<LogoutData, ThrowOnError>,
) =>
	(options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>(
		{ url: "/auth/logout", ...options },
	);

/**
 * Refresh
 */
export const refresh = <ThrowOnError extends boolean = false>(
	options?: Options<RefreshData, ThrowOnError>,
) =>
	(options?.client ?? client).post<
		RefreshResponses,
		RefreshErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/refresh",
		...options,
	});

/**
 * Register
 */
export const register = <ThrowOnError extends boolean = false>(
	options: Options<RegisterData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		RegisterResponses,
		RegisterErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/register",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Create Game
 */
export const createGame = <ThrowOnError extends boolean = false>(
	options: Options<CreateGameData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		CreateGameResponses,
		CreateGameErrors,
		ThrowOnError
	>({
		responseType: "json",
		security: [{ scheme: "bearer", type: "http" }],
		url: "/games/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Join Game
 */
export const joinGame = <ThrowOnError extends boolean = false>(
	options: Options<JoinGameData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		JoinGameResponses,
		JoinGameErrors,
		ThrowOnError
	>({
		responseType: "json",
		security: [{ scheme: "bearer", type: "http" }],
		url: "/games/{game_id}/join",
		...options,
	});

/**
 * Start Game
 */
export const startGame = <ThrowOnError extends boolean = false>(
	options: Options<StartGameData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		StartGameResponses,
		StartGameErrors,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/games/{game_id}/start",
		...options,
	});

/**
 * Get Game State
 */
export const getGameState = <ThrowOnError extends boolean = false>(
	options: Options<GetGameStateData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		GetGameStateResponses,
		GetGameStateErrors,
		ThrowOnError
	>({
		responseType: "json",
		security: [{ scheme: "bearer", type: "http" }],
		url: "/games/{game_id}/state",
		...options,
	});
