// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	CreateGameGamesPostData,
	CreateGameGamesPostErrors,
	CreateGameGamesPostResponses,
	GetGameStateGamesGameIdStateGetData,
	GetGameStateGamesGameIdStateGetErrors,
	GetGameStateGamesGameIdStateGetResponses,
	JoinGameGamesGameIdJoinPostData,
	JoinGameGamesGameIdJoinPostErrors,
	JoinGameGamesGameIdJoinPostResponses,
	LambdaGetData,
	LambdaGetResponses,
	LoginAppleAuthApplePostData,
	LoginAppleAuthApplePostErrors,
	LoginAppleAuthApplePostResponses,
	LoginAuthLoginPostData,
	LoginAuthLoginPostErrors,
	LoginAuthLoginPostResponses,
	LoginGoogleAuthGooglePostData,
	LoginGoogleAuthGooglePostErrors,
	LoginGoogleAuthGooglePostResponses,
	LogoutAuthLogoutPostData,
	LogoutAuthLogoutPostErrors,
	LogoutAuthLogoutPostResponses,
	RefreshAuthRefreshPostData,
	RefreshAuthRefreshPostErrors,
	RefreshAuthRefreshPostResponses,
	RegisterAuthRegisterPostData,
	RegisterAuthRegisterPostErrors,
	RegisterAuthRegisterPostResponses,
	StartGameGamesGameIdStartPostData,
	StartGameGamesGameIdStartPostErrors,
	StartGameGamesGameIdStartPostResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * <Lambda>
 */
export const lambdaGet = <ThrowOnError extends boolean = false>(
	options?: Options<LambdaGetData, ThrowOnError>,
) =>
	(options?.client ?? client).get<LambdaGetResponses, unknown, ThrowOnError>({
		responseType: "json",
		url: "/",
		...options,
	});

/**
 * Login Apple
 */
export const loginAppleAuthApplePost = <ThrowOnError extends boolean = false>(
	options: Options<LoginAppleAuthApplePostData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		LoginAppleAuthApplePostResponses,
		LoginAppleAuthApplePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/apple",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Login Google
 */
export const loginGoogleAuthGooglePost = <ThrowOnError extends boolean = false>(
	options: Options<LoginGoogleAuthGooglePostData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		LoginGoogleAuthGooglePostResponses,
		LoginGoogleAuthGooglePostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/google",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Login
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(
	options: Options<LoginAuthLoginPostData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		LoginAuthLoginPostResponses,
		LoginAuthLoginPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/login",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Logout
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(
	options?: Options<LogoutAuthLogoutPostData, ThrowOnError>,
) =>
	(options?.client ?? client).post<
		LogoutAuthLogoutPostResponses,
		LogoutAuthLogoutPostErrors,
		ThrowOnError
	>({ url: "/auth/logout", ...options });

/**
 * Refresh
 */
export const refreshAuthRefreshPost = <ThrowOnError extends boolean = false>(
	options?: Options<RefreshAuthRefreshPostData, ThrowOnError>,
) =>
	(options?.client ?? client).post<
		RefreshAuthRefreshPostResponses,
		RefreshAuthRefreshPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/refresh",
		...options,
	});

/**
 * Register
 */
export const registerAuthRegisterPost = <ThrowOnError extends boolean = false>(
	options: Options<RegisterAuthRegisterPostData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		RegisterAuthRegisterPostResponses,
		RegisterAuthRegisterPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		url: "/auth/register",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Create Game
 */
export const createGameGamesPost = <ThrowOnError extends boolean = false>(
	options: Options<CreateGameGamesPostData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		CreateGameGamesPostResponses,
		CreateGameGamesPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		security: [{ scheme: "bearer", type: "http" }],
		url: "/games/",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

/**
 * Join Game
 */
export const joinGameGamesGameIdJoinPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<JoinGameGamesGameIdJoinPostData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		JoinGameGamesGameIdJoinPostResponses,
		JoinGameGamesGameIdJoinPostErrors,
		ThrowOnError
	>({
		responseType: "json",
		security: [{ scheme: "bearer", type: "http" }],
		url: "/games/{game_id}/join",
		...options,
	});

/**
 * Start Game
 */
export const startGameGamesGameIdStartPost = <
	ThrowOnError extends boolean = false,
>(
	options: Options<StartGameGamesGameIdStartPostData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		StartGameGamesGameIdStartPostResponses,
		StartGameGamesGameIdStartPostErrors,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/games/{game_id}/start",
		...options,
	});

/**
 * Get Game State
 */
export const getGameStateGamesGameIdStateGet = <
	ThrowOnError extends boolean = false,
>(
	options: Options<GetGameStateGamesGameIdStateGetData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		GetGameStateGamesGameIdStateGetResponses,
		GetGameStateGamesGameIdStateGetErrors,
		ThrowOnError
	>({
		responseType: "json",
		security: [{ scheme: "bearer", type: "http" }],
		url: "/games/{game_id}/state",
		...options,
	});
