// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseURL: `${string}://${string}` | (string & {});
};

/**
 * AccessTokenResponse
 *
 * Public API response — only the short-lived access token.
 *
 * The refresh token is delivered via an httpOnly cookie by the router.
 */
export type AccessTokenResponse = {
	/**
	 * Access Token
	 */
	access_token: string;
	/**
	 * Token Type
	 */
	token_type?: string;
};

/**
 * CreateGameRequest
 */
export type CreateGameRequest = {
	/**
	 * Max Players
	 */
	max_players?: number;
};

/**
 * GameResponse
 */
export type GameResponse = {
	/**
	 * Game Id
	 */
	game_id: string;
	/**
	 * Max Players
	 */
	max_players: number;
	/**
	 * Player Count
	 */
	player_count: number;
	/**
	 * Status
	 */
	status: string;
};

/**
 * GameStateResponse
 */
export type GameStateResponse = {
	/**
	 * Current Player Id
	 */
	current_player_id: string | null;
	/**
	 * Free Parking Pot
	 */
	free_parking_pot: number;
	/**
	 * Game Id
	 */
	game_id: string;
	/**
	 * Phase
	 */
	phase: string;
	/**
	 * Players
	 */
	players: Array<{
		[key: string]: unknown;
	}>;
	/**
	 * Properties
	 */
	properties: {
		[key: string]: {
			[key: string]: unknown;
		};
	};
	/**
	 * Status
	 */
	status: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
	/**
	 * Email
	 */
	email: string;
	/**
	 * Password
	 */
	password: string;
};

/**
 * OAuthLoginRequest
 */
export type OAuthLoginRequest = {
	/**
	 * Device Hint
	 */
	device_hint?: string | null;
	/**
	 * Id Token
	 */
	id_token: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
	/**
	 * Display Name
	 */
	display_name: string;
	/**
	 * Email
	 */
	email: string;
	/**
	 * Password
	 */
	password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown;
	};
	/**
	 * Input
	 */
	input?: unknown;
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
};

/**
 * _ErrorResponse
 */
export type ErrorResponse = {
	/**
	 * Detail
	 */
	detail: string;
};

export type LoginAppleData = {
	body: OAuthLoginRequest;
	path?: never;
	query?: never;
	url: "/auth/apple";
};

export type LoginAppleErrors = {
	/**
	 * Authentication failed
	 */
	401: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginAppleError = LoginAppleErrors[keyof LoginAppleErrors];

export type LoginAppleResponses = {
	/**
	 * Successful Response
	 */
	200: AccessTokenResponse;
};

export type LoginAppleResponse = LoginAppleResponses[keyof LoginAppleResponses];

export type LoginGoogleData = {
	body: OAuthLoginRequest;
	path?: never;
	query?: never;
	url: "/auth/google";
};

export type LoginGoogleErrors = {
	/**
	 * Authentication failed
	 */
	401: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginGoogleError = LoginGoogleErrors[keyof LoginGoogleErrors];

export type LoginGoogleResponses = {
	/**
	 * Successful Response
	 */
	200: AccessTokenResponse;
};

export type LoginGoogleResponse =
	LoginGoogleResponses[keyof LoginGoogleResponses];

export type LoginData = {
	body: LoginRequest;
	path?: never;
	query?: never;
	url: "/auth/login";
};

export type LoginErrors = {
	/**
	 * Authentication failed
	 */
	401: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
	/**
	 * Successful Response
	 */
	200: AccessTokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/logout";
};

export type LogoutErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/refresh";
};

export type RefreshErrors = {
	/**
	 * Refresh token expired or invalid
	 */
	401: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
	/**
	 * Successful Response
	 */
	200: AccessTokenResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type RegisterData = {
	body: RegisterRequest;
	path?: never;
	query?: never;
	url: "/auth/register";
};

export type RegisterErrors = {
	/**
	 * Email already registered
	 */
	409: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
	/**
	 * Successful Response
	 */
	201: AccessTokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type CreateGameData = {
	body: CreateGameRequest;
	path?: never;
	query?: never;
	url: "/games/";
};

export type CreateGameErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateGameError = CreateGameErrors[keyof CreateGameErrors];

export type CreateGameResponses = {
	/**
	 * Successful Response
	 */
	201: GameResponse;
};

export type CreateGameResponse = CreateGameResponses[keyof CreateGameResponses];

export type JoinGameData = {
	body?: never;
	path: {
		/**
		 * Game Id
		 */
		game_id: string;
	};
	query?: never;
	url: "/games/{game_id}/join";
};

export type JoinGameErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type JoinGameError = JoinGameErrors[keyof JoinGameErrors];

export type JoinGameResponses = {
	/**
	 * Successful Response
	 */
	200: GameResponse;
};

export type JoinGameResponse = JoinGameResponses[keyof JoinGameResponses];

export type StartGameData = {
	body?: never;
	path: {
		/**
		 * Game Id
		 */
		game_id: string;
	};
	query?: never;
	url: "/games/{game_id}/start";
};

export type StartGameErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StartGameError = StartGameErrors[keyof StartGameErrors];

export type StartGameResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type StartGameResponse = StartGameResponses[keyof StartGameResponses];

export type GetGameStateData = {
	body?: never;
	path: {
		/**
		 * Game Id
		 */
		game_id: string;
	};
	query?: never;
	url: "/games/{game_id}/state";
};

export type GetGameStateErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetGameStateError = GetGameStateErrors[keyof GetGameStateErrors];

export type GetGameStateResponses = {
	/**
	 * Successful Response
	 */
	200: GameStateResponse;
};

export type GetGameStateResponse =
	GetGameStateResponses[keyof GetGameStateResponses];
