// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseURL: `${string}://${string}` | (string & {});
};

/**
 * AccessTokenResponse
 *
 * Public API response — only the short-lived access token.
 *
 * The refresh token is delivered via an httpOnly cookie by the router.
 */
export type AccessTokenResponse = {
	/**
	 * Access Token
	 */
	access_token: string;
	/**
	 * Token Type
	 */
	token_type?: string;
};

/**
 * CreateGameRequest
 */
export type CreateGameRequest = {
	/**
	 * Max Players
	 */
	max_players?: number;
};

/**
 * GameResponse
 */
export type GameResponse = {
	/**
	 * Game Id
	 */
	game_id: string;
	/**
	 * Max Players
	 */
	max_players: number;
	/**
	 * Player Count
	 */
	player_count: number;
	/**
	 * Status
	 */
	status: string;
};

/**
 * GameStateResponse
 */
export type GameStateResponse = {
	/**
	 * Current Player Id
	 */
	current_player_id: string | null;
	/**
	 * Free Parking Pot
	 */
	free_parking_pot: number;
	/**
	 * Game Id
	 */
	game_id: string;
	/**
	 * Phase
	 */
	phase: string;
	/**
	 * Players
	 */
	players: Array<{
		[key: string]: unknown;
	}>;
	/**
	 * Properties
	 */
	properties: {
		[key: string]: {
			[key: string]: unknown;
		};
	};
	/**
	 * Status
	 */
	status: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
	/**
	 * Email
	 */
	email: string;
	/**
	 * Password
	 */
	password: string;
};

/**
 * OAuthLoginRequest
 */
export type OAuthLoginRequest = {
	/**
	 * Device Hint
	 */
	device_hint?: string | null;
	/**
	 * Id Token
	 */
	id_token: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
	/**
	 * Display Name
	 */
	display_name: string;
	/**
	 * Email
	 */
	email: string;
	/**
	 * Password
	 */
	password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Context
	 */
	ctx?: {
		[key: string]: unknown;
	};
	/**
	 * Input
	 */
	input?: unknown;
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
};

/**
 * _ErrorResponse
 */
export type ErrorResponse = {
	/**
	 * Detail
	 */
	detail: string;
};

export type LambdaGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/";
};

export type LambdaGetResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type LoginAppleAuthApplePostData = {
	body: OAuthLoginRequest;
	path?: never;
	query?: never;
	url: "/auth/apple";
};

export type LoginAppleAuthApplePostErrors = {
	/**
	 * Authentication failed
	 */
	401: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginAppleAuthApplePostError =
	LoginAppleAuthApplePostErrors[keyof LoginAppleAuthApplePostErrors];

export type LoginAppleAuthApplePostResponses = {
	/**
	 * Successful Response
	 */
	200: AccessTokenResponse;
};

export type LoginAppleAuthApplePostResponse =
	LoginAppleAuthApplePostResponses[keyof LoginAppleAuthApplePostResponses];

export type LoginGoogleAuthGooglePostData = {
	body: OAuthLoginRequest;
	path?: never;
	query?: never;
	url: "/auth/google";
};

export type LoginGoogleAuthGooglePostErrors = {
	/**
	 * Authentication failed
	 */
	401: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginGoogleAuthGooglePostError =
	LoginGoogleAuthGooglePostErrors[keyof LoginGoogleAuthGooglePostErrors];

export type LoginGoogleAuthGooglePostResponses = {
	/**
	 * Successful Response
	 */
	200: AccessTokenResponse;
};

export type LoginGoogleAuthGooglePostResponse =
	LoginGoogleAuthGooglePostResponses[keyof LoginGoogleAuthGooglePostResponses];

export type LoginAuthLoginPostData = {
	body: LoginRequest;
	path?: never;
	query?: never;
	url: "/auth/login";
};

export type LoginAuthLoginPostErrors = {
	/**
	 * Authentication failed
	 */
	401: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LoginAuthLoginPostError =
	LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
	/**
	 * Successful Response
	 */
	200: AccessTokenResponse;
};

export type LoginAuthLoginPostResponse =
	LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type LogoutAuthLogoutPostData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/logout";
};

export type LogoutAuthLogoutPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type LogoutAuthLogoutPostError =
	LogoutAuthLogoutPostErrors[keyof LogoutAuthLogoutPostErrors];

export type LogoutAuthLogoutPostResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type LogoutAuthLogoutPostResponse =
	LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type RefreshAuthRefreshPostData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/auth/refresh";
};

export type RefreshAuthRefreshPostErrors = {
	/**
	 * Refresh token expired or invalid
	 */
	401: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type RefreshAuthRefreshPostError =
	RefreshAuthRefreshPostErrors[keyof RefreshAuthRefreshPostErrors];

export type RefreshAuthRefreshPostResponses = {
	/**
	 * Successful Response
	 */
	200: AccessTokenResponse;
};

export type RefreshAuthRefreshPostResponse =
	RefreshAuthRefreshPostResponses[keyof RefreshAuthRefreshPostResponses];

export type RegisterAuthRegisterPostData = {
	body: RegisterRequest;
	path?: never;
	query?: never;
	url: "/auth/register";
};

export type RegisterAuthRegisterPostErrors = {
	/**
	 * Email already registered
	 */
	409: ErrorResponse;
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type RegisterAuthRegisterPostError =
	RegisterAuthRegisterPostErrors[keyof RegisterAuthRegisterPostErrors];

export type RegisterAuthRegisterPostResponses = {
	/**
	 * Successful Response
	 */
	201: AccessTokenResponse;
};

export type RegisterAuthRegisterPostResponse =
	RegisterAuthRegisterPostResponses[keyof RegisterAuthRegisterPostResponses];

export type CreateGameGamesPostData = {
	body: CreateGameRequest;
	path?: never;
	query?: never;
	url: "/games/";
};

export type CreateGameGamesPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateGameGamesPostError =
	CreateGameGamesPostErrors[keyof CreateGameGamesPostErrors];

export type CreateGameGamesPostResponses = {
	/**
	 * Successful Response
	 */
	201: GameResponse;
};

export type CreateGameGamesPostResponse =
	CreateGameGamesPostResponses[keyof CreateGameGamesPostResponses];

export type JoinGameGamesGameIdJoinPostData = {
	body?: never;
	path: {
		/**
		 * Game Id
		 */
		game_id: string;
	};
	query?: never;
	url: "/games/{game_id}/join";
};

export type JoinGameGamesGameIdJoinPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type JoinGameGamesGameIdJoinPostError =
	JoinGameGamesGameIdJoinPostErrors[keyof JoinGameGamesGameIdJoinPostErrors];

export type JoinGameGamesGameIdJoinPostResponses = {
	/**
	 * Successful Response
	 */
	200: GameResponse;
};

export type JoinGameGamesGameIdJoinPostResponse =
	JoinGameGamesGameIdJoinPostResponses[keyof JoinGameGamesGameIdJoinPostResponses];

export type StartGameGamesGameIdStartPostData = {
	body?: never;
	path: {
		/**
		 * Game Id
		 */
		game_id: string;
	};
	query?: never;
	url: "/games/{game_id}/start";
};

export type StartGameGamesGameIdStartPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StartGameGamesGameIdStartPostError =
	StartGameGamesGameIdStartPostErrors[keyof StartGameGamesGameIdStartPostErrors];

export type StartGameGamesGameIdStartPostResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type StartGameGamesGameIdStartPostResponse =
	StartGameGamesGameIdStartPostResponses[keyof StartGameGamesGameIdStartPostResponses];

export type GetGameStateGamesGameIdStateGetData = {
	body?: never;
	path: {
		/**
		 * Game Id
		 */
		game_id: string;
	};
	query?: never;
	url: "/games/{game_id}/state";
};

export type GetGameStateGamesGameIdStateGetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetGameStateGamesGameIdStateGetError =
	GetGameStateGamesGameIdStateGetErrors[keyof GetGameStateGamesGameIdStateGetErrors];

export type GetGameStateGamesGameIdStateGetResponses = {
	/**
	 * Successful Response
	 */
	200: GameStateResponse;
};

export type GetGameStateGamesGameIdStateGetResponse =
	GetGameStateGamesGameIdStateGetResponses[keyof GetGameStateGamesGameIdStateGetResponses];
