// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AccessTokenResponse
 *
 * Public API response — only the short-lived access token.
 *
 * The refresh token is delivered via an httpOnly cookie by the router.
 */
export type AccessTokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * CreateGameDTO
 */
export type CreateGameDto = {
    /**
     * Max Players
     */
    max_players: number;
};

/**
 * ErrorResponseModel
 */
export type ErrorResponseModel = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * OAuthLoginRequest
 */
export type OAuthLoginRequest = {
    /**
     * Device Hint
     */
    device_hint?: string | null;
    /**
     * Id Token
     */
    id_token: string;
};

/**
 * Player
 */
export type Player = {
    /**
     * Balance
     */
    balance?: number;
    /**
     * Consecutive Doubles
     */
    consecutive_doubles?: number;
    /**
     * Get Out Of Jail Cards
     */
    get_out_of_jail_cards?: number;
    /**
     * In Jail
     */
    in_jail?: boolean;
    /**
     * Is Bankrupt
     */
    is_bankrupt?: boolean;
    /**
     * Jail Turns
     */
    jail_turns?: number;
    /**
     * Name
     */
    name: string;
    /**
     * Player Id
     */
    player_id?: string;
    /**
     * Position
     */
    position?: number;
};

/**
 * ReadGameDTO
 */
export type ReadGameDto = {
    /**
     * Game Id
     */
    game_id: string;
    /**
     * Max Players
     */
    max_players: number;
    /**
     * Players
     */
    players: Array<Player>;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * _ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

export type LoginAppleData = {
    body: OAuthLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/apple';
};

export type LoginAppleErrors = {
    /**
     * Authentication failed
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAppleError = LoginAppleErrors[keyof LoginAppleErrors];

export type LoginAppleResponses = {
    /**
     * Successful Response
     */
    200: AccessTokenResponse;
};

export type LoginAppleResponse = LoginAppleResponses[keyof LoginAppleResponses];

export type LoginGoogleData = {
    body: OAuthLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type LoginGoogleErrors = {
    /**
     * Authentication failed
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginGoogleError = LoginGoogleErrors[keyof LoginGoogleErrors];

export type LoginGoogleResponses = {
    /**
     * Successful Response
     */
    200: AccessTokenResponse;
};

export type LoginGoogleResponse = LoginGoogleResponses[keyof LoginGoogleResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Authentication failed
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: AccessTokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Refresh token expired or invalid
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Successful Response
     */
    200: AccessTokenResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterErrors = {
    /**
     * Email already registered
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: AccessTokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type CreateGameData = {
    body: CreateGameDto;
    path?: never;
    query?: never;
    url: '/games/';
};

export type CreateGameErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponseModel;
    /**
     * Game already exists
     */
    409: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGameError = CreateGameErrors[keyof CreateGameErrors];

export type CreateGameResponses = {
    /**
     * Successful Response
     */
    201: ReadGameDto;
};

export type CreateGameResponse = CreateGameResponses[keyof CreateGameResponses];

export type GetGameData = {
    body?: never;
    path: {
        /**
         * Game Id
         */
        game_id: string;
    };
    query?: never;
    url: '/games/{game_id}';
};

export type GetGameErrors = {
    /**
     * Unauthorized
     */
    401: ErrorResponseModel;
    /**
     * Game not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGameError = GetGameErrors[keyof GetGameErrors];

export type GetGameResponses = {
    /**
     * Successful Response
     */
    200: ReadGameDto;
};

export type GetGameResponse = GetGameResponses[keyof GetGameResponses];

export type JoinGameData = {
    body?: never;
    path: {
        /**
         * Game Id
         */
        game_id: string;
    };
    query?: never;
    url: '/games/{game_id}/join';
};

export type JoinGameErrors = {
    /**
     * Game not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JoinGameError = JoinGameErrors[keyof JoinGameErrors];

export type JoinGameResponses = {
    /**
     * Successful Response
     */
    200: ReadGameDto;
};

export type JoinGameResponse = JoinGameResponses[keyof JoinGameResponses];
