/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games/index'
import { Route as AuthenticatedGamesGameIdRouteRouteImport } from './routes/_authenticated/games/$gameId/route'
import { Route as AuthenticatedGamesGameIdIndexRouteImport } from './routes/_authenticated/games/$gameId/index'
import { Route as AuthenticatedGamesGameIdLobbyRouteImport } from './routes/_authenticated/games/$gameId/lobby'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesGameIdRouteRoute =
  AuthenticatedGamesGameIdRouteRouteImport.update({
    id: '/games/$gameId',
    path: '/games/$gameId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGamesGameIdIndexRoute =
  AuthenticatedGamesGameIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGamesGameIdRouteRoute,
  } as any)
const AuthenticatedGamesGameIdLobbyRoute =
  AuthenticatedGamesGameIdLobbyRouteImport.update({
    id: '/lobby',
    path: '/lobby',
    getParentRoute: () => AuthenticatedGamesGameIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdRouteRouteWithChildren
  '/games/': typeof AuthenticatedGamesIndexRoute
  '/games/$gameId/lobby': typeof AuthenticatedGamesGameIdLobbyRoute
  '/games/$gameId/': typeof AuthenticatedGamesGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/games': typeof AuthenticatedGamesIndexRoute
  '/games/$gameId/lobby': typeof AuthenticatedGamesGameIdLobbyRoute
  '/games/$gameId': typeof AuthenticatedGamesGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/games/$gameId': typeof AuthenticatedGamesGameIdRouteRouteWithChildren
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
  '/_authenticated/games/$gameId/lobby': typeof AuthenticatedGamesGameIdLobbyRoute
  '/_authenticated/games/$gameId/': typeof AuthenticatedGamesGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/games/$gameId'
    | '/games/'
    | '/games/$gameId/lobby'
    | '/games/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/games'
    | '/games/$gameId/lobby'
    | '/games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/games/$gameId'
    | '/_authenticated/games/'
    | '/_authenticated/games/$gameId/lobby'
    | '/_authenticated/games/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/$gameId': {
      id: '/_authenticated/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthenticatedGamesGameIdRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games/$gameId/': {
      id: '/_authenticated/games/$gameId/'
      path: '/'
      fullPath: '/games/$gameId/'
      preLoaderRoute: typeof AuthenticatedGamesGameIdIndexRouteImport
      parentRoute: typeof AuthenticatedGamesGameIdRouteRoute
    }
    '/_authenticated/games/$gameId/lobby': {
      id: '/_authenticated/games/$gameId/lobby'
      path: '/lobby'
      fullPath: '/games/$gameId/lobby'
      preLoaderRoute: typeof AuthenticatedGamesGameIdLobbyRouteImport
      parentRoute: typeof AuthenticatedGamesGameIdRouteRoute
    }
  }
}

interface AuthenticatedGamesGameIdRouteRouteChildren {
  AuthenticatedGamesGameIdLobbyRoute: typeof AuthenticatedGamesGameIdLobbyRoute
  AuthenticatedGamesGameIdIndexRoute: typeof AuthenticatedGamesGameIdIndexRoute
}

const AuthenticatedGamesGameIdRouteRouteChildren: AuthenticatedGamesGameIdRouteRouteChildren =
  {
    AuthenticatedGamesGameIdLobbyRoute: AuthenticatedGamesGameIdLobbyRoute,
    AuthenticatedGamesGameIdIndexRoute: AuthenticatedGamesGameIdIndexRoute,
  }

const AuthenticatedGamesGameIdRouteRouteWithChildren =
  AuthenticatedGamesGameIdRouteRoute._addFileChildren(
    AuthenticatedGamesGameIdRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGamesGameIdRouteRoute: typeof AuthenticatedGamesGameIdRouteRouteWithChildren
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGamesGameIdRouteRoute:
    AuthenticatedGamesGameIdRouteRouteWithChildren,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
