class GameError(Exception): ...


class GameNotFoundError(GameError): ...


class OptimisticLockError(GameError): ...


class GameAlreadyExistsError(GameError): ...


class GameAlreadyStartedError(GameError): ...
